import MagnifyIcon from "./search-zoom-in.svg";
import PlusIcon from "./plus.svg";
import SmileyEmoji from "./smiley.svg";
import PaperClipIcon from "./paperclip.svg";
import MicrophoneIcon from "./microphone.svg";
import GearIcon from "./gear.svg";
import MagnifyPlus from "./magnify-plus.svg";
import MagnifyMinus from "./magnify-minus.svg";
import Chevron from "./chevron.svg";
import TickIcon from "./tick.svg";
import ReloadIcon from "./reload.svg";
import SentIcon from "./tick-sent.svg";
import DoubleTickIcon from "./double-tick.svg";
import ExclamationIcon from "./exclamation.svg";
import LeftArrow from "./left-arrow.svg";
import SendIcon from "./send.svg";
import ClockIcon from "./clock.svg";
import VideoIcon from "./video.svg";
import TelephoneIcon from "./telephone.svg";
import GoogleNeutralRoundNAIcon from "./google_neutral_rd_na.svg";

export { ClockIcon, ExclamationIcon, MagnifyIcon, GearIcon, GoogleNeutralRoundNAIcon, PlusIcon, SmileyEmoji, PaperClipIcon, MicrophoneIcon, MagnifyPlus, MagnifyMinus, Chevron, TickIcon, ReloadIcon, SentIcon, DoubleTickIcon, LeftArrow, SendIcon, VideoIcon, TelephoneIcon };
